name: Sinbad Production Workflow
on:
  push:
    tags:
    - production_*
env:
  RELEASE_TYPE: Production
jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Pages Production
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.extract_version.outputs.RELEASE_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Install npm packages
      uses: "./.github/actions/npm_install_from_cache"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: production
    - name: Versioning
      uses: "./.github/actions/tag"
      with:
        release_type: production
    - name: Extract version
      id: extract_version
      run: echo "RELEASE_VERSION=${version}" >> $GITHUB_OUTPUT
    - name: Publish to Cloudflare Pages Production
      uses: "./.github/actions/publish_to_pages_production"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Upload to vercel
      id: dr_action
      uses: 'deriv-com/shared-actions/.github/actions/vercel_DR_publish@master'
      with:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
          ENVIRONMENT: Production
          VERCEL_SCOPE: deriv
          ALIAS_DOMAIN_URL: 'sinbad-dr.binary.sx'
    - name: Send Slack Notification on Vercel Publish failure
      uses: "deriv-com/shared-actions/.github/actions/send_slack_notification@master"
      if: steps.dr_action.outcome != 'success'
      with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: "$RELEASE_TYPE Vercel Deployment for sinbad.software with version ${{ needs.build_and_test.outputs.RELEASE_VERSION }} has Failed"

  send_slack_notification:
      name: Send Slack notification
      runs-on: ubuntu-latest
      if: always()
      needs: [build_test_and_publish]
      steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5
      - name: Create Slack Message
        id: create_slack_message
        run: |
          if [ $WORKFLOW_CONCLUSION == "success" ]; then
            echo "MESSAGE=$RELEASE_TYPE Release succeeded for Sindabad with version ${{ needs.build_test_and_publish.outputs.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
          else
            echo "MESSAGE=$RELEASE_TYPE Release failed for Sindabad with version ${{ needs.build_test_and_publish.outputs.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
          fi
      - name: Send Slack Notification
        uses: "deriv-com/shared-actions/.github/actions/send_slack_notification@master"
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: ${{ steps.create_slack_message.outputs.MESSAGE }}
