name: Sinbad Staging Workflow
on:
  push:
    branches:
    - master

jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Tag
      uses: "./.github/actions/tag"
    - name: Install npm packages
      uses: "./.github/actions/npm_install_from_cache"
    - name: Invalidate Cache
      uses: ./.github/actions/invalidate_master_cache
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: staging
    - name: Publish to Cloudflare Pages Staging
      uses: "./.github/actions/publish_to_pages_staging"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
